Repository Here-You/here-you-backend, pull requests merged in 2024-02, with the labels that each got.

#18 [Feat] 시그니처: 페이지 및 내용 상세보기 API 개발 #13
  src/response/response-code.enum.ts
  src/signature/domain/signature.entity.ts
  src/signature/domain/signature.like.entity.ts
  src/signature/domain/signature.page.entity.ts
  src/signature/dto/author-signature.dto.ts
  src/signature/dto/detail-signature.dto.ts
  src/signature/dto/header-signature.dto.ts
  src/signature/dto/page-signature.dto.ts
  src/signature/dto/tmp-userId.dto.ts
  src/signature/signature.controller.ts
  src/signature/signature.module.ts
  src/signature/signature.service.ts
  src/user/user.service.ts
Labels: ✨ Fearture, 💛 유정

#29 [Feat] 시그니처: 좋아요 기능 API 개발 #17
  src/response/response-code.enum.ts
  src/signature/domain/signature.entity.ts
  src/signature/domain/signature.like.entity.ts
  src/signature/dto/like-signature.dto.ts
  src/signature/signature.controller.ts
  src/signature/signature.service.ts
  src/user/user.following.entity.ts
Labels: ✨ Fearture, 💛 유정

#50 [Feat] 시그니처: 시그니처 수정 및 삭제, 좋아요 목록 API 구현 #30
  src/response/response-code.enum.ts
  src/signature/domain/signature.entity.ts
  src/signature/domain/signature.like.entity.ts
  src/signature/domain/signature.page.entity.ts
  src/signature/dto/get-like-list.dto.ts
  src/signature/dto/home-signature.dto.ts
  src/signature/dto/like-profile.dto.ts
  src/signature/signature.controller.ts
  src/signature/signature.service.ts
Labels: ✨ Fearture, 💛 유정

#52 [Feat] 탐색탭 메인 화면: 인기 급상승, 최신 시그니처 API 구현 #51
  src/app.module.ts
  src/main.ts
  src/response/response-code.enum.ts
  src/search/dto/cover-signature.dto.ts
  src/search/dto/get-search-main.dto.ts
  src/search/search.controller.ts
  src/search/search.module.ts
  src/search/search.service.ts
  src/signature/domain/signature.entity.ts
  src/signature/domain/signature.page.entity.ts
  src/user/user.entity.ts
  src/user/user.service.ts
Labels: ✨ Fearture, 💛 유정

#55 [Feat] 탐색: 키워드로 검색하기 API 구현
  src/response/response-code.enum.ts
  src/search/search.controller.ts
  src/search/search.service.ts
  src/signature/domain/signature.entity.ts
Labels: ✨ Fearture, 💛 유정

#57 [Refactor] 시그니처, 탐색 @UserGaurd 리팩토링 #56
  src/search/search.controller.ts
  src/signature/domain/signature.entity.ts
  src/signature/domain/signature.page.entity.ts
  src/signature/dto/author-signature.dto.ts
  src/signature/dto/tmp-userId.dto.ts
  src/signature/signature.controller.ts
  src/signature/signature.service.ts
Labels: 💛 유정, 🔨 Refactor

#71 [HotFix] 시그니처 좋아요 여부 에러 해결
  src/signature/signature.service.ts
  src/user/user.service.ts
Labels: 🐛 BugFix, 💛 유정

#72 [Fix] 탐색 메인 화면: 인기, 최신 시그니처 정렬 함수 로직 변경
  src/search/search.service.ts
Labels: 💛 유정, 🔨 Refactor

#74 [Refactor] 시그니처 이미지 업로드 방식 수정 #73
  src/signature/dto/detail-signature.dto.ts
  src/signature/dto/page-signature.dto.ts
  src/signature/dto/response-page-signature.dto.ts
  src/signature/signature.service.ts
Labels: 💛 유정, 🔨 Refactor

#113 fix: 메이트 탐색 - 현재 로그인한 사용자 닉네임 추가 #112
  src/mate/dto/mate-recommend-profile.dto.ts
  src/mate/dto/mate-with-common-location-response.dto.ts
  src/mate/mate.service.ts
Labels: 💛 유정, 🔨 Refactor

#119 [Fix] 메이트 탐색 데이터 누락 및 오류 수정 #115
  src/mate/mate.service.ts
  src/signature/signature.service.ts
  src/user/user.service.ts
Labels: 🐛 BugFix, 💛 유정

#122 fix: 시그니처 상세보기 작성자 객체 null값 에러 해결
  src/signature/signature.controller.ts
  src/signature/signature.service.ts
Labels: 🐛 BugFix, 💛 유정

#126 [Refactor] 시그니처 상세보기: Response Dto 수정 #123
  src/mate/mate.controller.ts
  src/search/search.controller.ts
  src/search/search.service.ts
  src/signature/signature.controller.ts
  src/signature/signature.service.ts
Labels: 🐛 BugFix, 💛 유정

#133 [Feat] 메이트 마이페이지 프로필 정보 API 개발 #128
  src/mate/dto/mate-profile-response.dto.ts
  src/mate/dto/mate-profile-signature.dto.ts
  src/mate/mate.controller.ts
  src/mate/mate.service.ts
  src/response/response-code.enum.ts
  src/search/dto/get-search-main.dto.ts
  src/search/dto/signature-cover.dto.ts
  src/search/search.controller.ts
  src/search/search.service.ts
  src/signature/signature.controller.ts
Labels: ✨ Fearture, 💛 유정

#135 [Feat] 메이트 프로필 정보 팔로워, 팔로잉 수 추가 #128
  src/mate/dto/mate-profile-response.dto.ts
  src/mate/mate.service.ts
  src/user/user.service.ts
Labels: ✨ Fearture, 💛 유정

#139 feat: 메이트 시그니처 가져오기 api 구현 #134
  src/mate/dto/mate-signature-cover.dto.ts
  src/mate/mate.controller.ts
  src/mate/mate.service.ts
  src/response/response-code.enum.ts
Labels: ✨ Fearture, 💛 유정

#146 [Fix/Refactor] 메이트 프로필 팔로우 여부 데이터 누락 해결 및 게시물 수 속성 추가
  src/mate/dto/mate-profile-response.dto.ts
  src/mate/mate.service.ts
  src/signature/signature.service.ts
Labels: ✨ Fearture, 🐛 BugFix, 💛 유정

#164 fix: 여행 규칙 댓글 무한 스크롤 초기값 설정
  src/rule/rule.service.ts
Labels: 🐛 BugFix, 💛 유정

#165 fix: 여행 규칙 댓글 정렬 순서 변경
  src/rule/rule.service.ts
Labels: 🐛 BugFix, 💛 유정

#193 [BugFix] 시그니처 수정하기 이미지 예외처리 구현하기 #192
  src/signature/signature.service.ts
  src/user/user.service.ts
Labels: 🐛 BugFix, 💛 유정

#195 [Feat] 시그니처 댓/답글 수정하기 api 개발 #180
  src/signature/dto/comment/get-signature-comment.dto.ts
  src/signature/signature.comment.controller.ts
  src/signature/signature.comment.service.ts
Labels: ✨ Fearture, 💛 유정

#202 [Feat] 시그니처 댓글 삭제하기 구현
  src/signature/signature.comment.controller.ts
  src/signature/signature.comment.service.ts
Labels: ✨ Fearture, 💛 유정

#209 Refactor: 시그니처 댓글 삭제 권한 변경 #207
  src/signature/dto/comment/get-signature-comment.dto.ts
  src/signature/signature.comment.service.ts
Labels: 💛 유정, 🔨 Refactor

#229 Refactor: 탐색 메인 api 분리 및 닉네임 누락 해결 #222
  src/search/dto/get-search-main.dto.ts
  src/search/search.controller.ts
  src/search/search.service.ts
  src/signature/domain/signature.entity.ts
  src/user/optional.user.guard.ts
Labels: 🐛 BugFix, 💛 유정

#232 fix : 팔로우리스트 탈퇴한 회원 제외
  src/user/user.service.ts
Labels: 🐛 BugFix, 💚 예원

#233 [Refactor] 탈퇴한 사용자 필터링 추가 #230
  src/mate/mate.service.ts
  src/search/search.service.ts
  src/signature/domain/signature.entity.ts
  src/signature/domain/signature.like.entity.ts
  src/signature/signature.service.ts
  src/user/user.service.ts
Labels: 🐛 BugFix, 💛 유정

#234 fix: 탐색 - 시그니처 썸네일 가져오기 버그 해결
  src/search/search.service.ts
  src/signature/domain/signature.page.entity.ts
  src/signature/signature.service.ts
Labels: 🐛 BugFix, 💛 유정

#235 [hotfix] 최신 시그니처 중복 push 오류 해결
  src/search/search.service.ts
Labels: 🐛 BugFix, 💛 유정

#236 [Refactor] 홈 시그니처 최신순으로 반환하기
  src/signature/signature.service.ts
Labels: 💛 유정, 🔨 Refactor

#237 [Refactor] 메이트 탐색 검색 결과 최신순 정렬
  src/search/search.service.ts
Labels: 💛 유정, 🔨 Refactor

#239 [BugFix] 팔로워 목록에서 isFollow = true 버그 픽스
  src/follow/follow.service.ts
Labels: 🐛 BugFix, 💛 유정

#238 Feature/#224
  src/follow/follow.service.ts
  src/rule/dto/detail.rule.dto.ts
  src/rule/dto/get-comment.dto.ts
  src/rule/rule.service.ts
  src/user/user.service.ts
Labels: 🐛 BugFix, 💚 예원

#241 fix : 댓글 글자 수 변경
  src/comment/domain/comment.entity.ts
Labels: 🐛 BugFix, 💚 예원

#242 fix : 규칙 제목 글자 수 제한 수정
  src/rule/domain/detail.rule.entity.ts
  src/rule/domain/rule.main.entity.ts
  src/rule/domain/rule.sub.entity.ts
Labels: 🐛 BugFix, 💚 예원
